seed: 42
epochs: 1
batch_size: 128
lr: 0.001

# Data loading
num_workers: 2
pin_memory: true

# Device preference (we'll use this later)
device: "cuda"

dataset:
  name: cifar10
  root: "./data"
  image_size: 32

